import React, { useState, useEffect } from 'react';
import { useTheme } from '../contexts/ThemeContext';
import { getThemeClasses } from '../utils/themeUtils';
import { RegulatoryCompliance } from '../utils/regulatoryCompliance';
import { jsPDF } from 'jspdf';

const RegulatoryComplianceManager = ({ onClose }) => {
  const { isDark } = useTheme();
  const theme = getThemeClasses(isDark);
  const [activeTab, setActiveTab] = useState('dashboard');
  const [complianceData, setComplianceData] = useState({
    overallScore: 0,
    frameworks: {},
    risks: [],
    reports: []
  });

  const handleTabClick = (tabId) => {
    setActiveTab(tabId);
  };

  useEffect(() => {
    loadComplianceData();
  }, []);

  const loadComplianceData = () => {
    const frameworks = ['GRI', 'SASB', 'TCFD', 'BRSR'];
    const frameworkScores = {};
    
    frameworks.forEach(fw => {
      const score = Math.floor(Math.random() * 40) + 60;
      frameworkScores[fw] = score;
    });

    const risks = [
      { id: 1, title: 'Missing GHG Scope 3 Data', severity: 'High', impact: 'Compliance Gap' },
      { id: 2, title: 'Incomplete Diversity Metrics', severity: 'Medium', impact: 'Reporting Risk' },
      { id: 3, title: 'Outdated Governance Policies', severity: 'Low', impact: 'Minor Gap' }
    ];

    setComplianceData({
      overallScore: Math.floor(Object.values(frameworkScores).reduce((a, b) => a + b, 0) / frameworks.length),
      frameworks: frameworkScores,
      risks,
      reports: JSON.parse(localStorage.getItem('complianceReports') || '[]')
    });
  };

  const generateComplianceReport = () => {
    const report = {
      id: Date.now(),
      title: `Regulatory Compliance Report - ${new Date().toLocaleDateString()}`,
      generated: new Date().toISOString(),
      frameworks: complianceData.frameworks,
      overallScore: complianceData.overallScore,
      riskCount: complianceData.risks.length
    };

    const existingReports = JSON.parse(localStorage.getItem('complianceReports') || '[]');
    const updatedReports = [report, ...existingReports].slice(0, 10);
    localStorage.setItem('complianceReports', JSON.stringify(updatedReports));
    
    setComplianceData(prev => ({ ...prev, reports: updatedReports }));
    
    const auditEntry = RegulatoryCompliance.createAuditTrail(
      'REPORT_GENERATED',
      localStorage.getItem('currentUser') || 'system',
      { reportId: report.id, type: 'compliance' }
    );
    
    const auditTrail = JSON.parse(localStorage.getItem('auditTrail') || '[]');
    localStorage.setItem('auditTrail', JSON.stringify([auditEntry, ...auditTrail]));
    
    alert('✅ Compliance report generated successfully!');
  };

  const downloadReportAsPDF = (report) => {
    const pdf = new jsPDF();
    
    pdf.setFontSize(20);
    pdf.setTextColor(0, 102, 51);
    pdf.text('REGULATORY COMPLIANCE REPORT', 20, 30);
    
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`Generated: ${new Date(report.generated).toLocaleString()}`, 20, 50);
    pdf.text(`Report ID: ${report.id}`, 20, 60);
    
    pdf.setFontSize(16);
    pdf.setTextColor(0, 102, 51);
    pdf.text('Overall Compliance Score', 20, 80);
    pdf.setFontSize(24);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`${report.overallScore}%`, 20, 95);
    
    pdf.setFontSize(16);
    pdf.setTextColor(0, 102, 51);
    pdf.text('Framework Compliance', 20, 120);
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    let yPos = 135;
    Object.entries(report.frameworks).forEach(([framework, score]) => {
      pdf.text(`${framework}: ${score}%`, 20, yPos);
      yPos += 15;
    });
    
    pdf.setFontSize(16);
    pdf.setTextColor(0, 102, 51);
    pdf.text('Risk Summary', 20, yPos + 20);
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`Total Identified Risks: ${report.riskCount}`, 20, yPos + 35);
    
    yPos += 60;
    pdf.setFontSize(14);
    pdf.setTextColor(0, 102, 51);
    pdf.text('Compliance Status', 20, yPos);
    yPos += 15;
    
    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    const complianceItems = [
      'GRI Standards: Framework alignment verified',
      'SASB Standards: Industry-specific metrics tracked',
      'TCFD Guidelines: Climate risk assessment completed',
      'BRSR Requirements: Regulatory compliance maintained'
    ];
    
    complianceItems.forEach(item => {
      pdf.text(`• ${item}`, 25, yPos);
      yPos += 10;
    });
    
    pdf.setFontSize(10);
    pdf.setTextColor(128, 128, 128);
    pdf.text('Generated by ESG Regulatory Compliance System', 20, 280);
    
    pdf.save(`regulatory-compliance-report-${report.id}.pdf`);
  };

  const assessRisks = () => {
    const newRisks = [
      ...complianceData.risks,
      {
        id: Date.now(),
        title: 'New Risk Identified',
        severity: 'Medium',
        impact: 'Assessment Required',
        identified: new Date().toISOString()
      }
    ];
    setComplianceData(prev => ({ ...prev, risks: newRisks }));
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className={`w-full max-w-6xl max-h-[90vh] rounded-2xl shadow-2xl overflow-hidden ${theme.bg.primary} ${theme.border.primary}`}>
        <div className={`p-6 border-b ${theme.border.secondary}`}>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-2xl">⚖️</span>
              <h2 className={`text-2xl font-bold ${theme.text.primary}`}>Regulatory Compliance</h2>
            </div>
            <button onClick={onClose} className={`p-2 rounded-lg ${theme.hover.card} ${theme.text.secondary}`}>✕</button>
          </div>
          
          <div className="flex gap-4 mt-4">
            {[
              { id: 'dashboard', label: 'Dashboard', icon: '📊' },
              { id: 'reports', label: 'Reports', icon: '📋' },
              { id: 'risks', label: 'Risk Assessment', icon: '⚠️' }
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => handleTabClick(tab.id)}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-all ${
                  activeTab === tab.id 
                    ? 'bg-blue-600 text-white' 
                    : `${theme.text.secondary} ${theme.hover.card}`
                }`}
              >
                <span>{tab.icon}</span>
                {tab.label}
              </button>
            ))}
          </div>
        </div>

        <div className="p-6 overflow-y-auto max-h-[calc(90vh-200px)]">
          {activeTab === 'dashboard' && (
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <div className={`p-4 rounded-lg ${theme.bg.subtle} ${theme.border.primary}`}>
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-2xl">📊</span>
                    <h3 className={`font-semibold ${theme.text.primary}`}>Overall Score</h3>
                  </div>
                  <div className="text-3xl font-bold text-green-600">{complianceData.overallScore}%</div>
                </div>
                
                {Object.entries(complianceData.frameworks).map(([framework, score]) => (
                  <div key={framework} className={`p-4 rounded-lg ${theme.bg.subtle} ${theme.border.primary}`}>
                    <h3 className={`font-semibold ${theme.text.primary} mb-2`}>{framework}</h3>
                    <div className={`text-2xl font-bold ${score >= 80 ? 'text-green-600' : score >= 60 ? 'text-yellow-600' : 'text-red-600'}`}>
                      {score}%
                    </div>
                    <div className={`w-full bg-gray-200 rounded-full h-2 mt-2`}>
                      <div className={`h-2 rounded-full ${score >= 80 ? 'bg-green-600' : score >= 60 ? 'bg-yellow-600' : 'bg-red-600'}`} style={{width: `${score}%`}}></div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'reports' && (
            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <h3 className={`text-xl font-semibold ${theme.text.primary}`}>Compliance Reports</h3>
                <button
                  onClick={generateComplianceReport}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                >
                  📋 Generate Report
                </button>
              </div>
              
              <div className="space-y-3">
                {complianceData.reports.length === 0 ? (
                  <div className={`text-center py-8 ${theme.text.secondary}`}>
                    <span className="text-4xl mb-4 block">📋</span>
                    <p>No reports generated yet</p>
                    <p className="text-sm mt-2">Click "Generate Report" to create your first compliance report</p>
                  </div>
                ) : (
                  complianceData.reports.map(report => (
                    <div key={report.id} className={`p-4 rounded-lg ${theme.bg.subtle} ${theme.border.primary}`}>
                      <div className="flex justify-between items-start">
                        <div>
                          <h4 className={`font-semibold ${theme.text.primary}`}>{report.title}</h4>
                          <p className={`text-sm ${theme.text.secondary} mt-1`}>
                            Generated: {new Date(report.generated).toLocaleString()}
                          </p>
                          <p className={`text-sm ${theme.text.secondary}`}>
                            Overall Score: {report.overallScore}% | Risks: {report.riskCount}
                          </p>
                        </div>
                        <button 
                          onClick={() => downloadReportAsPDF(report)}
                          className="px-3 py-1 bg-green-600 text-white rounded text-sm hover:bg-green-700"
                        >
                          📄 Download PDF
                        </button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}

          {activeTab === 'risks' && (
            <div className="space-y-4">
              <div className="flex justify-between items-center">
                <h3 className={`text-xl font-semibold ${theme.text.primary}`}>Risk Assessment</h3>
                <button
                  onClick={assessRisks}
                  className="px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors"
                >
                  ⚠️ Assess Risks
                </button>
              </div>
              
              <div className="space-y-3">
                {complianceData.risks.map(risk => (
                  <div key={risk.id} className={`p-4 rounded-lg ${theme.bg.subtle} ${theme.border.primary}`}>
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className={`font-semibold ${theme.text.primary}`}>{risk.title}</h4>
                        <p className={`text-sm ${theme.text.secondary}`}>Impact: {risk.impact}</p>
                      </div>
                      <span className={`px-2 py-1 rounded text-xs font-medium ${
                        risk.severity === 'High' ? 'bg-red-100 text-red-800' :
                        risk.severity === 'Medium' ? 'bg-yellow-100 text-yellow-800' :
                        'bg-green-100 text-green-800'
                      }`}>
                        {risk.severity}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default RegulatoryComplianceManager;